### ISSUE TITLE
less@2.6 not work with node@6

### ISSUE THREAD

**Issue by jaredleechn** [ant-tool/component-init#7]
目前就发现了这一种组合有问题，编译 css 文件不能

其它的：

less@2.6 with node@5
less@2.7 with node@6

都没问题

**Comment by wenshiqi0** [comment]
> less@2.6 lessc

```
 var pathToMap = path.dirname(sourceMapFileInline ? output : sourceMapOptions.sourceMapFullFilename),
     pathToInput = path.dirname(sourceMapOptions.sourceMapInputFilename);
```

> less@2.7 lessc

```
var pathToMap = path.dirname(sourceMapFileInline ? output : sourceMapOptions.sourceMapFullFilename || '.'),
    pathToInput = path.dirname(sourceMapOptions.sourceMapInputFilename || '.');
```

2.7的代码比2.6的代码多做了一次空值检测，我估计是node在path这一层做了更严格的检测改动，不接受一些空值所以导致直接报错了，2.7多加了一层检测，规避了这个问题。

**Comment by soda-x** [comment]
对应的讨论在这个 issue 内 

https://github.com/less/less.js/issues/2881

**Comment by soda-x** [comment]
https://github.com/ant-tool/component-init/blob/master/boilerplate/package.json#L47 已经是 `2.7.1` 了
